# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: HiroSystems.Clarinet
PackageVersion: 1.4.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/hirosystems/clarinet/releases/download/v1.4.1/clarinet-windows-x64.msi
  InstallerSha256: BA3D00336398D0293477BF7BC0757A558DC0B5BBA2F0A9D102780ED7EA45037D
  ProductCode: '{A712C81E-8506-4A2D-AB5F-F98006B2D50F}'
ManifestType: installer
ManifestVersion: 1.4.0
